# Use the official Node.js image from the Docker Hub
FROM node:22.13.1

# Set the working directory inside the container
WORKDIR /usr/src/frontend

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# Expose the port the app runs on
EXPOSE 5173

# Command to run the Node.js server
CMD ["npm", "run" , "dev" ]